### ISSUE TITLE
Question - GoToStep Programmatically

### ISSUE THREAD

**Issue by xVishera** [madoar/ng2-archwizard#17]
Hello! 

First of all, congratulations for the great work here, this is a wonderfull component for angular.

I have a simple question about moving from onestep to another. 

Is there any way to do it at the typescript side ?

For example, at Step1 I must perform a confirmation message before going on, If the user click on "Ok" it triggers a function on the typescript, and at that function I should move the user to Step2 or Step3.

I tried to implement that by setting a boolean variable and setting it to "canExit", but because of the proccess of the confirmation it doesn't worked as expected.

**Comment by madoar** [comment]
Nice to hear that you like the wizard component :)

About your question:
You can navigate the wizard through typescript.
To do this you need to inject an instance of your used `WizardComponent`:
```typescript
@ViewChild(WizardComponent)
public wizard: WizardComponent;
```

Next you can call the method `wizard.goToStep(destinationStepIndex)` to navigate to a given step.
Please beware, that you can't go to an arbitrary step. 
You can only go to an arbitrary previous step or the direct next step.
An exception to the "direct next step" rule is if the next step is an optional step, in this case it's possible to jump over it and you can go to the second next step and so on.
In addition `canExit` needs to return or be true, so that the current step can be left, otherwise the wizard will remain in its current step.

If you have any questions left feel free to ask.

**Comment by madoar** [comment]
Let me correct myself:
If you use `wizard.goToStep(destinationStepIndex)` you should be able to enter any step, as long as you can exit the current step.

The "previous step or direct next step" condition is currently checked inside the `wizard.canGoToStep(stepIndex)` method, which you don't need to call. 
Please be aware, that this can change in a later version!

**Comment by xVishera** [comment]
Thank you for the great explanation sir. It worked as expected BUT I think I've found a bug.

I've a wizard with 5 steps, no one is optional.

When I initiate the wizard, if the user meet some requeriments I guide him to step 3 (index 2) directly. In this case, the step 2 keeps grey and I cant navigate forward to step 4, I've to go to the previous step then go forward again.

**Comment by madoar** [comment]
The problem in your usecase is that you've an incomplete step before your current step, namely step 2. 
This causes the `canGoToStep` method, which gets called by the `nextStep` directive, to return false.
Currently you have two ways to solve the problem:

- you specify the second step as an optional step
- you replace the `nextStep` by a manual call of `wizard.goToStep(destinationStepIndex)`

I think that what you want goes in the direction of #7, which is about enabling the user enter an arbitrary step, disregarding the question whether a previous step to the destination step is incomplete or not.

**Comment by xVishera** [comment]
At the moment, to solve the "problem" and gets the second step marked as completed, In my cenário I called "wizard.nextStep" two times, it moved the user to the third step and let step two marked as completed.

**Comment by LastCodeDE** [comment]
This doesn't work anymore
