### ISSUE TITLE
Wizard and Wizard-step not getting recognised when used in Modules

### ISSUE THREAD

**Issue by relics123** [madoar/ng2-archwizard#24]
![screen_shot](https://user-images.githubusercontent.com/13677250/29495594-1b1aba16-85e0-11e7-8d60-c9959374f3a2.jpeg)
Hi ,
I have one Main AppModule and inside that I have one sub Module Subscription Module which I am loading through Routes.

The Wizard and Wizard-step is not getting rendered properly.

If I put the HTML and CSS together in any of the component in the Main App Module. It works.
But I want it to be in Subscription Module only.

I imported WizardModule in Subscription Module and added it in the Providers section also.

Kindly help me with this Issue.

Thanks
Manish Pandit

**Comment by madoar** [comment]
Hmm, without providing your source code it's hard for me to point out the source of the problem. 
My suggestion is to take a look at the demo application at https://github.com/madoar/ng2-archwizard-demo, because it is created using submodules. Each demo case is created as a submodule that imports the `WizardModule`.

If this doesn't help you feel free to write a comment.

**Comment by relics123** [comment]
Hi Madaor,

Thanks for the reply.
(I am new to Angualr2 so please bare with me for the basic things)
Actually I am doing a lazy module load through routes.
I forget to import 'wizardmodule' in the sub module.

https://github.com/fredguile/ng2-md-datatable/issues/37 (helped me)

It is working now.

Thanks
Manish Pandit
