### ISSUE TITLE
there's tooltip on whole page included Step Title !

### ISSUE THREAD

**Issue by Al-Sharif** [madoar/ng2-archwizard#25]

**Comment by Al-Sharif** [comment]
solution : $("wizard-step").removeAttr("title"); 🗡

**Comment by madoar** [comment]
I've asked myself for quite some time where the title comes from... 

Thanks for the bug report!
I must confess that I'm not sure how to handle this issue, because the only good way I know of to solve this problem is to rename the `title` input of the wizard steps. 
The problem with this approach is, that this would break the backwards compatibility of the library, which I would like to prevent. 
Maybe someone has an idea how to solve this in a good way?

**Comment by mrsweaters** [comment]
I vote the attribute be renamed to `wizard-step-title`, seeing as how a native DOM attributes already exists with the name `title`.

**Comment by Al-Sharif** [comment]
I'm with @mrsweaters , you should change `title` to `wizard-step-title` , and no problem if you change something will fixes issues forever even in backwards compatibility, you should push new major release with attention for your changes. 

I would like if you can make an option to make step title is clickable or not. while i had requirements in this application (http://muscatcapital-sa.azurewebsites.net) to prevent the user to moving between steps via its links.

thank you for your cooperation

**Comment by madoar** [comment]
Just as a short heads up:
I've decided to rename `title` to `stepTitle` and `titleTemplate` to `stepTitleTemplate`. I hope this solves the problems.

@Al-Sharif I've taken a look at your website, it seems like you require an inverted option for the navigation bar?

**Comment by mrsweaters** [comment]
@madoar Thanks!
