### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using *ngFor on wizard Step

### ISSUE THREAD

**Issue by aishwaryagarg** [madoar/ng2-archwizard#40]
Getting following error when I tried to use *ngFor on wizard Step.
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
Please help!

**Comment by madoar** [comment]
I need a bit more information to help you.
Which version of `ng2-archwizard` are you using? Where does the error occur (did you get any line information)? How does your code look like?

**Comment by aishwaryagarg** [comment]
I am using 1.6.2 version.
Please have a look on code below-

<wizard>
  <wizard-step title="demo" *ngFor="let wizard of field.wizardSteps">
    Content of Step 1
    <button type="button" nextStep>Next Step</button>
    <button type="button" goToStep="2">Go directly to third Step</button>
  </wizard-step>
</wizard>

**Comment by aishwaryagarg** [comment]
Please let me know If you need some more information

**Comment by madoar** [comment]
Can you please also add your typescript code, belonging to the snippet?
Ideally it would be nice to have a working code sample that produces your described error.

**Comment by aishwaryagarg** [comment]
I just followed you documentation, It works fine untill all wizardsteps are seprate, But as soon as I have added ngFor this issue generates.
my array has a  very simple structure
`wizardSteps = [
{"title": "abc", "title": "pqr", "title": "xyz" }
]`

**Comment by madoar** [comment]
It looks to me like you're creating the `wizardSteps` wrong, because you're only creating a single json object inside with three `title` fields.
Sadly I haven't found the time yet to test `*ngFor` in combination with the wizard steps yet.
It would be best if you could provide a fully executable sample that produces your described error during runtime.

**Comment by scozma** [comment]
I have the same issue, which seems to be a feature of Angular (and not a bug) in dev mode. 
I don't know what causes it when using *ngFor with ng2-archwizard, but **calling enableProdMode( )** when bootstrapping the app prevents the exception from being thrown. So this means the problem will appear only on dev mode. Some guys say something about using a setTimeout, but it was not the case for me. You can find more here:
https://github.com/angular/angular/issues/6005

**Comment by madoar** [comment]
@scozma thank you for telling us how to solve the problem!
I've done some tests too and also stumbled over the previously stated error.
I believe that to solve this problem in a more clean way it's required to improve the lifecycle hocks used in ng2-archwizard.

This currently has no high priority for me. 
In addition please use `ngFor` with caution in combination with the wizard steps! The reason being, that if you insert a new step **before** the currently entered step, the wizard will have a corrupted state, because the current step index isn't automatically updated and a not completed step is inserted.

**Comment by scozma** [comment]
Here is a solution for still working on dev mode:

```
import { ChangeDetectorRef } from '@angular/core';

constructor(private _changeDetectionRef : ChangeDetectorRef} { }

ngAfterViewInit() : void {
    // Force another change detection in order to fix the dialog error
    this._changeDetectionRef.detectChanges();
}
```

**Comment by madoar** [comment]
@scozma where should this code be inserted?

**Comment by madoar** [comment]
@scozma do you want to provide an example for this in the demo repository (https://github.com/madoar/ng2-archwizard-demo) and submit a PR?

**Comment by scozma** [comment]
@madoar - Do you know why I am getting this error while trying to push the changes?

```
$ git push origin fix-for-ngFor
remote: Permission to madoar/ng2-archwizard-demo.git denied to scozma.
fatal: unable to access 'https://github.com/madoar/ng2-archwizard-demo.git/': The requested URL returned error: 403
```

**Comment by madoar** [comment]
@scozma you need to create a fork of the project first (https://help.github.com/articles/fork-a-repo/).
Afterwards you can push to your fork and open a new PR to the main repository.

**Comment by scozma** [comment]
@madoar - Thanks! I didn't know I had to fork first. I created the PR:
https://github.com/madoar/ng2-archwizard-demo/pull/13
Please let me know if it's ok. Thanks!
