### ISSUE TITLE
perform goToStep programatically

### ISSUE THREAD

**Issue by gmarab** [madoar/ng2-archwizard#58]
Hi @madoar,

I'm trying to change the step from the program using

@ViewChild(WizardComponent)
public wizard: WizardComponent;

but when I try to call, for example, this.wizard.goToStep (1); I always get the error that goToStep is not defined in wizard.

what am I doing wrong ?
would not you have an example to show?

Thanks in advance.

**Comment by madoar** [comment]
Starting with version `2.0.0` I've moved some methods to other components/classes.
One such group of methods are the navigation methods, to which `goToStep` belongs.
These methods are now contained in the class `NavigationMode`, which you can get via `wizard.navigation`. 

I would advise you to use the directives provided by `ng2-archwizard` whenever possible, to prevent internal changes made to `ng2-archwizard`, from breaking your application.

**Comment by gioragutt** [comment]
@madoar regarding that, that makes the library rather limiting, if you have to rely on directives and not be able to programmatically control stuff.

The way to expose such behavior is to provide a service, which will wrap all this behavior, and users of this service won't have to be aware of internal breaking changes.

**Comment by achimha** [comment]
The project was updated to version 2.0 which means there are breaking changes. I believe this is fairly normal.

**Comment by gioragutt** [comment]
@achimha the problem is not that there were breaking changes. one can argue that a major version upgrade is a reason for breaking API changes, but that's not the point.

The point is that currently, there is no way to expose such behavior WITHOUT either braking changes or limitations on internal implementation, which are both bad things.

Deciding on an API, and exposing it through a service, regardless of the internal implementation of the directives and components, is the way to go.

If there were to be breaking changes in the service API, that's still not as bad as component or directive breaking API changes, because services can be wrapped as well. It is also true for components and/or directives, but that requires component/directive wrapping, which is far less nice than service wrapping, because you're not taking advantage of angular's DI.

**Comment by madoar** [comment]
With version `2.0.0` I split the wizard component in three classes:
- `WizardComponent` (the view/gui component)
- `WizardState` an injectable service, containing the state/model of a wizard component
- `NavigationMode` an interface containing functionality to navigate the wizard.

The `NavigationMode` interface was necessary in my eyes to make it easier to implement multiple navigation behaviors, i.e. `strict`, `semi-strict` and `free`. Each of these behaviors is realized by extending the `NavigationMode` class.
In addition I've created the `WizardState` class to make a hard split between the view and the model, because the old `WizardComponent` class had too many lines of code in my eyes.

With theses changes done, I believe the wizard to not require any breaking changes currently. Therefore I think it's ok to use these classes as an API to access the model of the wizard.
The problem is, that I can't promise you that these classes won't change, because that depends on future functionality, which may be added. 
The `WizardState`, which also contains the `NavigationMode` of a wizard component, can be obtained either by calling `wizard.model`. Alternatively you can also try to inject it directly from inside a wizard component.

Related to this:
#31 seems to be related to this. My problem with the topic of providing a Service API to access a wizard component is, that I know no use case where this is necessary and therefore don't know what I should provide. 
To solve this it would be best if you tell me how this Service API should look like and how it should be used. Afterwards we can discuss, how this can be achieved best.

**Comment by gioragutt** [comment]
@madoar couldn't see it in the README. Is there any `canContinue` directive to wizard steps?
f.e if I want to be able to continue only if the form is valid

**Comment by madoar** [comment]
@gioragutt the wizard steps provide a `[canExit]` and `[canEnter]` input. This input can be either a boolean or a function providing a boolean and taking a `MovingDirection` enum. These inputs are then used to determine if the wizard can transition from the current step to the destination step.

**Comment by gioragutt** [comment]
@madoar perhaps i'm talking about something more subtle.

can you use `canExit` to block traversal to a single direction? aka, can you validate that you can go backward from the step but not forward?

**Comment by gioragutt** [comment]
I guess I can do `canEnter` on the next step, but perheps I want the step to be responsible for this logic, not the next step.

**Comment by madoar** [comment]
Both the `[canExit]` and `[canEnter]` inputs can be set to a function, taking a `MovingDirection` and returning a boolean (or even `Promise<boolean>`) :)
Therefore you can either set `[canExit]` of the current step or `[canEnter]` of the destination step.

**Comment by gioragutt** [comment]
Oh, so they receive the direction that is being validated. So basically this is the method would be invoked twice each traversal. Pretty nice idea.

The demo app is nice tbh, but it's missing code snippets.
You show a lot of cases, but you don't actually show what's going on being, without having to go to github and scan the repo.

**Comment by madoar** [comment]
Yes I'm missing a code environment and an easy way to insert the code from the corresponding files :(
If you have a solution for that, feel free to extend/improve the demo and open a new PR :)

**Comment by gioragutt** [comment]
@madoar I might. I'd look into how others are doing that, f.e [Angular Material](http://material.angular.io).
