### ISSUE TITLE
'wizard-step' is not a known element

### ISSUE THREAD

**Issue by burakkilic** [madoar/ng2-archwizard#60]
Hello,

I'm using Angular 4 in my project. I added ng2-archwizard to my project like in the manual. I'm getting a lot of errors starting with

    'wizard-step' is not a known element

Where am I wrong?

**Comment by madoar** [comment]
Without taking a look at your project it's hard for me to say where the problem is located.
My first guess would be that `ng2-archwizard` hasn't been added correctly to the project, i.e. that it either hasn't been added to the `package.json` file and therefore to your `node_modules` folder, or that it hasn't been imported to your angular app-module.
If this isn't the reason, I will need to take a look at your source code, to give better suggestions.

**Comment by burakkilic** [comment]
Hello, thank you for the comments.

1 - I added "ng2-archwizard" to package.json as "ng2-archwizard": "2.0.0" and it is in "node_modules" folder.

2 - In  my top most module "app.module.ts" , I imported the library as

**Comment by madoar** [comment]
This looks ok to me, how does the rest of your project look like?
How did you create it?
Maybe a look at https://github.com/madoar/ng2-archwizard-demo helps. This is a functional angular 4 project using `ng2-archwizard`.

**Comment by burakkilic** [comment]
I think I found out the problem. I have imported the library on top most app module. I also have child modules and it worked when I import the library into them.

Sorry about that, and thank you for your time.
