### ISSUE TITLE
Not able to override Style

### ISSUE THREAD

**Issue by aishwaryagarg** [madoar/ng2-archwizard#61]
Hi,
Congratulations for creating such a great wizard!
But I am facing issue while trying to write custom css.
1. the custom style is not reflected until I use ::ng-deep.
2. The custom style doesn't get preference if I not use !important

My main concern is, we can't use !important, as our project can be use by other projects as dependency. So adding Important at our level will reduce our platforms capability to be customized.

for better understanding please see the snippet below-

>`::ng-deep .horizontal.large-filled ul.steps-indicator li.current:after {
background-color: red;
} `

**Comment by madoar** [comment]
Nice to hear that you like the wizard :)
@avril-verhaeghen is currently working on a PR to enable customization of the css styles (see #46). Currently there are still some things to fix before I can merge this PR. 
An example how this can then be used can be found here: https://github.com/madoar/ng2-archwizard-demo/pull/11/files

**Comment by madoar** [comment]
Closed by #92, which enables the definition of custom styles outside `ng2-archwizard` to modify the look of the wizard.

To define a custom style, it's required to use `!important` to override css properties set by the wizard, otherwise the browser will automatically use the layout defined by `ng2-archwizard`.
