### ISSUE TITLE
programmatically calling a goToStep Issue

### ISSUE THREAD

**Issue by AhmadShahid** [madoar/ng2-archwizard#63]
Hello!

I am facing an issue when programmatically call a goToStep method on my component it says.

> ERROR TypeError: this.wizard.goToStep is not a function.

I followed the exact same step that you specified on a ticket no [#17](https://github.com/madoar/ng2-archwizard/issues/17)

I m using a version  "ng2-archwizard": ",2.0.0".

**Comment by madoar** [comment]
Starting with version `2.0.0` I've refactored the codebase and moved some functionality to new components/classes.
One of these functionalities is the navigation logic. This logic can now be found inside the `NavigationMode` class, which has three implementations.
To access the navigation mode you have two choices:
- you can access the navigation mode via an injected wizard: `wizard.navigation`
- you can access the navigation via an injected `WizardState`: `wizardState.navigationMode`

If you have any remaining questions feel free to ask them.

**Comment by sajeelmunir** [comment]
Hi Madoar,

I'm having the same issue since updated to "ng2-archwizard" 2.1.0?

I would be grateful if you could provide me working code example?

Cheers,

**Comment by AhmadShahid** [comment]
@sajeelmunir use this.wizard.navigation.goToStep instead of accessing it on a wizard instance. it solves my problem

**Comment by sajeelmunir** [comment]
Shook-riya Shahid!

**Comment by ggoforth** [comment]
Having a similar problem, in my component I've got:

`import {WizardState} from 'ng2-archwizard/dist';`

and then in the constructor:

```
  constructor(private wizard: WizardState) {
  }
```

and I'm getting the following error:

`ERROR Error: Uncaught (in promise): Error: No provider for WizardState!
Error: No provider for WizardState!`

This is in a module that implements the actual `<wizard>` component, so I know things are wired up ok at the module level.  Any ideas?

**Comment by madoar** [comment]
Hmm,
I must confess that I haven't tried to import `WizardState` directly from a component defined outside `ng2-archwizard` (even if I wrote in the `README` that it should be possible).

I have two ideas that may help:
1. can you try to add an `@Inject()` to your constructor call? I.e.: 
   `constructor(@Inject(WizardState) private wizard: WizardState) { ... }`
2. can you try to add a provider to either your angular application module `providers: [WizardState]` or to your component

If both ideas don't work can you try to directly inject the `WizardComponent` into your custom component: `constructor(private wizard: WizardComponent)`

**Comment by ggoforth** [comment]
I will try those things.  Right now I'm going the route of @ViewChild(WizardComponent) and I can get the wizard component that way.  How would I go about programmatically navigating with that?  I see `this.wizard.navigation.wizardState` but that yields:

```
 Property 'wizardState' is protected and only accessible within class 'NavigationMode' and its subclasses.```

Just not quite sure where I should be getting at the wizardState with the ViewChild (or if I'm going about this the wrong way).  Also, I gotta say, this is a great component, and it's awesome how active you are and how quickly you respond.  Thanks!

**Comment by madoar** [comment]
Nice to get such good feedback. Thanks a lot. About your problem:

You're misunderstanding the affiliation of the model parts, i.e. `WizardState` and `NavigationMode`.
The navigation mode is part of the wizard state, therefore it can be found in a field inside `WizardState`.
About the competencies of both classes:
- `WizardState` only contains the state of the wizard, and is therefore a model class in the MVC scheme
- `NavigationMode` is used to navigate inside the wizard, and should therefore be used as a controller. The problem is, that `ng2-archwizard` provides three `NavigationMode` implementations. To make it transparent for the user which navigation mode he's using, and to make it easy to access, it's saved inside the wizard state.

The names of the fields inside `WizardComponent` aren't the best.
You can access the `WizardState` instance of your `WizardComponent` via `wizard.model`.
The `NavigationMode` can be accessed via `wizard.navigation`, which is only a shortcut for `wizard.model.navigationMode`.
For more details, take a look at https://github.com/madoar/ng2-archwizard/blob/master/src/components/wizard.component.ts

**Comment by ggoforth** [comment]
Ah, you're right,  I was confusing those.  So, I added WizardState as a provider in my main app module and can now import and inject it into my component that implements the wizard!  Thanks for that suggestion.  With the WizardState now (implemented as I did in my original comment), I don't see the `navigation` mode (via navigation  or navigationMode).  The object looks like:

![screenshot 2017-11-01 12 09 50](https://user-images.githubusercontent.com/1167712/32293641-07f2751e-bf01-11e7-92aa-88afac6d2559.png)

This is `console.log`'d in the ngOnInit of the parent component that implements the `<wizard>`.

**Comment by madoar** [comment]
The problem seems to be, that angular doesn't use the `WizardState` created by the `WizardComponent`, but creates a new `WizardState` object in your module.
You would need to configure angular somehow to inject the `WizardState` created in the `WizardComponent`, but I don't know how this can be done.

I think until we find a solution to this problem, you'll need to take the detour through the `WizardComponent` object.

**Comment by ggoforth** [comment]
Yep, got it working.  I neglected to checkout the prototype of the navigationMode.  My current findings are that when using the wizard ViewChild, the navigationMode is set to a string:

this.wizard.navigationMode === 'strict'; // true

If you navigate in a bit further (through `model`) we can get to the navigationMode.  I had neglected to look into the prototype of the navigationMode, but sure enough there was `goToStep` :) 

So this is what worked for me:

```
  // At the top of my component class that implements the <wizard>
  @ViewChild(WizardComponent)
  public wizard: WizardComponent;

  // then later, this works great
  this.wizard.model.navigationMode.goToStep(1)
```

Thanks for your help @madoar!

**Comment by madoar** [comment]
@ggoforth nice to hear :)
As a short note, the following should be shorter and equally work:

```typescript
  // At the top of my component class that implements the <wizard>
  @ViewChild(WizardComponent)
  public wizard: WizardComponent;

  // then later, this works great
  this.wizard.navigation.goToStep(1)
```

**Comment by ggoforth** [comment]
Indeed it does, thank you!

**Comment by oliviya** [comment]
hi, should i import WizardComponent,
 if yes, is it from import {WizardComponent} from 'ng2-archwizard/dist'; 
i did as above but got this error 'Cannot read property 'goToStep' of undefined', can you please help

**Comment by vagostep** [comment]
@oliviya I have the same issue. I print in console the value of wizard:WizardComponent and see this:
![console](https://user-images.githubusercontent.com/15386436/35576771-d89e8502-05ad-11e8-9ecf-26de6890c237.jpg)

But when i print the value of wizard.navigation got `undefined`

So when i use the method goToStep fails.

How to solve this?

**Comment by madoar** [comment]
@vagostep your screenshot suggests that in the first line `navigation` is not undefined.
Can you post us your code, so that I can check what exactly happens?
In addition it would be useful to know which version of `ng2-archwizard` you're using and with which browser you've tested it.

@oliviya sorry for my late response, somehow I overlooked your post. 
Can you please tell me which version of `ng2-archwizard` you're using and with which browser you've tested it on?

**Comment by igioya** [comment]
Hi @madoar, how are you?
I need initialize the state of navigation to free, to can go to step x when initialize my component.
Can you help me?
Thank you!

**Comment by Kievbuy** [comment]
> @oliviya I have the same issue. I print in console the value of wizard:WizardComponent and see this:
> ![console](https://user-images.githubusercontent.com/15386436/35576771-d89e8502-05ad-11e8-9ecf-26de6890c237.jpg)
> 
> But when i print the value of wizard.navigation got `undefined`
> 
> So when i use the method goToStep fails.
> 
> How to solve this @madoar?
> 
> I use this:
> `@ViewChild(WizardComponent) public wizard: WizardComponent;`

`this.wizard.goToStep(3);` woking fine

**Comment by madoar** [comment]
@Kievbuy I'm not sure how and where the browser accesses `wizard.navigation`.
When you look at the first output in your screenshot, you see that `wizard.navigation` seems to be defined (it seems to be of type `StrictNavigationMode`).
